string name                       # identifier for this constraint
string label                      # human-readable label
string[] types                    # OWL types of this constraint
knowrob_motion_constraints/MotionConstraintTemplate template # constraint template this is derived from
bool active                       # flag indicating if constraint is active
float64 constrLowerLimit          # lower limit of the constraint range
float64 constrUpperLimit          # upper limit of the constraint range
