string name                       # identifier for this constraint
string label                      # human-readable label
string[] types                    # OWL types of this constraint
string toolFeature                # OWL class definition describing the tool feature
string worldFeature               # OWL class definition describing the world feature
string refFeature                 # Tf frame describing the reference feature
float64 constrLowerLimit          # lower limit of the constraint range
float64 constrUpperLimit          # upper limit of the constraint range
